### ISSUE TITLE
Cross build for ARM on MacOS

### ISSUE THREAD

**Issue by hejfelix** [s-zeng/dhall-python#47] opened 2022-03-22 09:46 UTC
We would love to use this on the new ARM macbooks, but it is currently unavailable in pypi for that platform. Would it be easy to add it?

**Comment by s-zeng** [comment] 2022-03-22 16:32
Duplicate of https://github.com/s-zeng/dhall-python/issues/32

The big blocker is that github actions doesn't have an M1 builder, and I don't have access to an M1 machine to build artifacts myself. You can still compile from source, but automatic pypi publishing is hard for this reason.

**Closed by s-zeng** 2022-03-22 16:32 UTC
