### ISSUE TITLE
[Installation Bug] Pip installation of the dhall package fails on M2 Macbooks

### ISSUE THREAD

**Issue by bageren** [s-zeng/dhall-python#143] opened 2023-04-27 12:56 UTC
python version: 3.10.2
pip version:  23.1.2
macOS: 13.3.1
chip: Apple M2 Pro

When I run `pip install dhall`, I get the following error:

```Collecting dhall
  Using cached dhall-0.1.9.tar.gz (25.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      💥 maturin failed
        Caused by: The following metadata fields in `package.metadata.maturin` section of Cargo.toml are removed since maturin 0.14.0: classifier, please set them in pyproject.toml as PEP 621 specifies.
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/tv/xyv2127n0sn6gxfdk24rczd00000gp/T/pip-modern-metadata-dkx0j1hl', '--interpreter', '/Users/dkJeBaRa/.asdf/installs/python/3.10.2/bin/python3.10']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/tv/xyv2127n0sn6gxfdk24rczd00000gp/T/pip-modern-metadata-dkx0j1hl --interpreter /Users/dkJeBaRa/.asdf/installs/python/3.10.2/bin/python3.10`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

From what I can see it seems like you have fixed the metadata fields issue in later versions, but 0.1.9 seems to be the only package version available to me. Any plans to release a version that is compatible with my system?

**Comment by s-zeng** [comment] 2023-04-30 21:29
Hi, can you tell me the output of


```
pip install --force-reinstall -v "dhall==0.1.14"
```

**Comment by bageren** [comment] 2023-05-01 08:02
@s-zeng 

```
pip install --force-reinstall -v "dhall==0.1.14"
Using pip 23.1.2 from /Users/dkJeBaRa/Library/trifrost/venv/lib/python3.10/site-packages/pip (python 3.10)
ERROR: Could not find a version that satisfies the requirement dhall==0.1.14 (from versions: 0.1.9)
ERROR: No matching distribution found for dhall==0.1.14
```

**Comment by s-zeng** [comment] 2023-05-02 20:15
This is a duplicate of https://github.com/s-zeng/dhall-python/issues/32#issuecomment-1374371697

Once I am done with my wedding and honeymoon, I should have some time to fix this. In the mean time, try [installing directly from Github](https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github)

**Closed** 2023-05-02 20:15 UTC
